name: Build Static HTML in DOCS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run BUILD
        run: chmod +x ./build.sh && ./build.sh

      - name: Build CSS
        run: |
          # Copy the CSS file to the docs directory
          sass sass/main.scss docs/main.css        

      - name: Deploy to GitHub
        run: |
          # Check if there are any changes
          if [[ $(git status --porcelain) ]]; then
            # If there are changes, add, commit, and push
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "Generated HTML files"
            git push -f
          else
            echo "No changes to commit."
          fi
