name: Build Static HTML in DOCS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run BUILD
        run: chmod +x ./build.sh && ./build.sh
